CC = gcc

P1 = part1
P2 = part2
P3 = part3

CFLAGS = -ansi -Wall -O2

part1:
	$(CC) $(P1).c $(CFLAGS) -o $(P1)

runPart1:
	$(CC) $(P1).c $(CFLAGS) -o $(P1)
	./$(P1)

part2:
	$(CC) $(P2).c $(CFLAGS) -o $(P2)

runPart2:
	$(CC) $(P2).c $(CFLAGS) -o $(P2)
	./$(P2)

part3:
	$(CC) $(P3).c $(CFLAGS) -o $(P3)

runPart3:
	$(CC) $(P3).c $(CFLAGS) -o $(P3)
	./$(P3)

clearAll:
	rm ./$(P1) 
	rm ./$(P2) 
	rm ./$(P3)